import { Mapping } from '../types';

const config: Mapping = {
  sources: [
    {
      // 1
      parameters: {
        blend: { cc: 1 },
        diff: { cc: 2 },
        feedback: { cc: 3 },
        selfModulate: { cc: 4 },
        mod1: { cc: 5 },
        mod2: { cc: 6 },
        mod3: { cc: 7 },
        brightness: { cc: 8 },
        rotation: { cc: 9 },
        pixelate: { cc: 10 },
        scale: { cc: 11 },
        colorama: { cc: 12 },
        modulate: { cc: 13 },
        modulateRotate: { cc: 14 },
        modulateScale: { cc: 15 },
        repeatXY: { cc: 16 },
        colorR: { cc: 17 },
        colorG: { cc: 18 },
        colorB: { cc: 19 },
        contrast: { cc: 20 },
      },
      switchSource: { note: 'F2' },
      reset: { note: 'F#2' },
    },
    {
      //2
      parameters: {
        blend: { cc: 21 },
        diff: { cc: 22 },
        feedback: { cc: 23 },
        selfModulate: { cc: 24 },
        mod1: { cc: 25 },
        mod2: { cc: 26 },
        mod3: { cc: 27 },
        brightness: { cc: 28 },
        rotation: { cc: 29 },
        pixelate: { cc: 30 },
        scale: { cc: 31 },
        colorama: { cc: 32 },
        modulate: { cc: 33 },
        modulateRotate: { cc: 34 },
        modulateScale: { cc: 35 },
        repeatXY: { cc: 36 },
        colorR: { cc: 37 },
        colorG: { cc: 38 },
        colorB: { cc: 39 },
        contrast: { cc: 40 },
      },
      switchSource: { note: 'A3' },
      reset: { note: 'A#3' },
    },
    // {
    //   // 3
    //   parameters: {
    //     blend: { cc: 41 },
    //     diff: { cc: 42 },
    //     feedback: { cc: 43 },
    //     selfModulate: { cc: 44 },
    //     mod1: { cc: 45 },
    //     mod2: { cc: 46 },
    //     mod3: { cc: 47 },
    //     brightness: { cc: 48 },
    //     rotation: { cc: 49 },
    //     pixelate: { cc: 50 },
    //     scale: { cc: 51 },
    //     colorama: { cc: 52 },
    //     modulate: { cc: 53 },
    //     modulateRotate: { cc: 54 },
    //     modulateScale: { cc: 55 },
    //     repeatXY: { cc: 56 },
    //     colorR: { cc: 57 },
    //     colorG: { cc: 58 },
    //     colorB: { cc: 59 },
    //     contrast: { cc: 60 },
    //   },
    //   switchSource: { note: 'D3' },
    //   reset: { note: 'D#3' },
    // },
    // {
    //   // 4
    //   parameters: {
    //     blend: { cc: 61 },
    //     diff: { cc: 62 },
    //     feedback: { cc: 63 },
    //     selfModulate: { cc: 64 },
    //     mod1: { cc: 65 },
    //     mod2: { cc: 66 },
    //     mod3: { cc: 67 },
    //     brightness: { cc: 68 },
    //     rotation: { cc: 69 },
    //     pixelate: { cc: 70 },
    //     scale: { cc: 71 },
    //     colorama: { cc: 72 },
    //     modulate: { cc: 73 },
    //     modulateRotate: { cc: 74 },
    //     modulateScale: { cc: 75 },
    //     repeatXY: { cc: 76 },
    //     colorR: { cc: 77 },
    //     colorG: { cc: 78 },
    //     colorB: { cc: 79 },
    //     contrast: { cc: 80 },
    //   },
    //   switchSource: { note: 'C3' },
    //   reset: { note: 'C#3' },
    // },
  ],
  keys: {
    shift: { note: 'A7' },
    lfo1: { note: 'B7' },
    lfo2: { note: 'C8' },
    audio: { note: 'A#7' },
  },
  presets: [
    { note: 'C#5' },
    { note: 'D5' },
    { note: 'D#5' },
    { note: 'E5' },
    { note: 'F6' },
    { note: 'F#6' },
    { note: 'G6' },
    { note: 'G#6' },
  ],
  lfosControl: [
    {
      rate: { cc: 81 },
      type: { cc: 82 },
    },
    {
      rate: { cc: 83 },
      type: { cc: 84 },
    },
  ],
};

export default config;
